# Generated by Django 4.1.7 on 2023-02-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted status')),
                ('file_upload', models.ImageField(blank=True, null=True, upload_to='media/avatar/')),
            ],
            options={
                'verbose_name': 'Generic file upload',
                'db_table': 'message_control_gen_file_upload',
                'ordering': ['id'],
            },
        ),
    ]
