# Generated by Django 4.1.7 on 2023-02-21 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_control', '0001_initial'),
        ('user_control', '0002_jwt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='jwt',
            options={'ordering': ['id'], 'verbose_name': 'Jwt'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted status'),
        ),
        migrations.AddField(
            model_name='jwt',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active status'),
        ),
        migrations.AddField(
            model_name='jwt',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated time'),
        ),
        migrations.AlterField(
            model_name='jwt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='jwt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated time'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='user_control_customer',
        ),
        migrations.AlterModelTable(
            name='jwt',
            table='user_control_jwt',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted status')),
                ('first_name', models.CharField(max_length=255, verbose_name='User first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='User last name')),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=6, verbose_name='User gender')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='User phone')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='User address')),
                ('number', models.CharField(blank=True, max_length=32, null=True, verbose_name='User address number')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='User city')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='User country')),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_avatar', to='message_control.genericfileupload', verbose_name='User avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
                'db_table': 'user_control_user_profile',
                'ordering': ['id'],
            },
        ),
    ]
